### ISSUE TITLE
Расширение возможности конфигурировать приложение

### ISSUE THREAD

**Issue by Ledarium** [Idvon/Pogodnik#3]
У заказчика сломался текстовый редактор для json файлов, поэтому он просит нас использовать [TOML](https://toml.io/en/)-файл для настройки. Также, его смущает использование непонятных API-ключей, и хочет использовать свой.

- Добавить возможность чтения конфига из произвольного toml или json файла. Предполагается корректность структуры в соответствии с примерами ниже
- Имя файла будет передано аргументом командной строки, например `python3 PoGoDnIk.py config.toml`. В случае, если имя файла не указано, выдавать ошибку
- Добавить чтение ключа из конфига. Если не указан ключ и он требуется для провайдера - выдавать ошибку

Примеры конфигов:
```json
{
"city_name": "Saint Petersburg",
"provider": {
  "name": "openweather",
  "api_key": "..."
}
}
```
```toml
city_name = "Saint Petersburg"
[provider]
name = "openweather"
api_key = "..."
```

**Comment by Idvon** [comment]
Здоровья заказчику!
